# Generated by Django 3.0.6 on 2020-06-19 05:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Construction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('construction_name', models.CharField(max_length=60, verbose_name='Nome da construção')),
                ('construction_date_start', models.DateField(verbose_name='Data de início')),
                ('construction_date_term', models.DateField(verbose_name='Data de entrega')),
            ],
        ),
        migrations.CreateModel(
            name='Diary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diary_date_day', models.DateField(verbose_name='Data do atual')),
                ('diary_construction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Diary.Construction')),
            ],
        ),
        migrations.CreateModel(
            name='Access',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('user_type', models.CharField(max_length=50, verbose_name='Tipo')),
                ('registration_mode', models.IntegerField(blank=True, null=True, verbose_name='Status do usuario')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Total_service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_service_manpower', models.IntegerField(verbose_name='Quantidade de mão de obra')),
                ('total_service_equipment', models.IntegerField(verbose_name='Quantidade de equipamento')),
                ('total_service_diary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Diary.Diary')),
            ],
        ),
        migrations.CreateModel(
            name='Observation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observation_description_service', models.TextField(verbose_name='Descrição do serviço')),
                ('observation_description', models.TextField(verbose_name='Observações')),
                ('observation_diary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Diary.Diary')),
            ],
        ),
        migrations.CreateModel(
            name='Indirect_labor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indirect_labor_description', models.CharField(max_length=40, verbose_name='Mão de obra indireta')),
                ('indirect_labor_amount', models.IntegerField(verbose_name='Quantidade')),
                ('indirect_labor_diary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Diary.Diary')),
            ],
        ),
        migrations.CreateModel(
            name='Equipment_construction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipment_construction_description', models.CharField(max_length=40, verbose_name='Equipamentos da obra')),
                ('equipment_construction_amount', models.IntegerField(verbose_name='Quantidade')),
                ('equipment_construction_diary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Diary.Diary')),
            ],
        ),
        migrations.CreateModel(
            name='Engineer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('engineer_name', models.CharField(max_length=50, verbose_name='Nome do engenheiro')),
                ('engineer_cnpj', models.CharField(max_length=50, verbose_name='CNPJ')),
                ('engineer_contact', models.CharField(max_length=50, verbose_name='Número de Contato')),
                ('engineer_street', models.CharField(max_length=50, verbose_name='Rua')),
                ('engineer_number', models.IntegerField(verbose_name='Número')),
                ('engineer_city', models.CharField(max_length=50, verbose_name='Cidade')),
                ('engineer_state', models.CharField(max_length=50, verbose_name='Estado')),
                ('engineer_cod', models.CharField(max_length=50, verbose_name='CEP')),
                ('user_access', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Direct_labor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direct_labor_description', models.CharField(max_length=40, verbose_name='Mão de obra direta')),
                ('direct_labor_amount', models.IntegerField(verbose_name='Quantidade')),
                ('direct_labor_diary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Diary.Diary')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=50, verbose_name='Nome do cliente')),
                ('customer_cnpj', models.CharField(max_length=50, verbose_name='CNPJ')),
                ('customer_contact', models.CharField(max_length=50, verbose_name='Número de Contato')),
                ('customer_street', models.CharField(max_length=50, verbose_name='Rua')),
                ('customer_number', models.IntegerField(verbose_name='Número')),
                ('customer_city', models.CharField(max_length=50, verbose_name='Cidade')),
                ('customer_state', models.CharField(max_length=50, verbose_name='Estado')),
                ('customer_cod', models.CharField(max_length=50, verbose_name='CEP')),
                ('engineer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Diary.Engineer')),
                ('user_access', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Contractor_labor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contractor_labor_description', models.CharField(max_length=40, verbose_name='Mão de Obra de Empreiteras')),
                ('contractor_labor_amount', models.IntegerField(verbose_name='Quantidade')),
                ('contractor_labor_diary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Diary.Diary')),
            ],
        ),
        migrations.CreateModel(
            name='Contractor_equipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contractor_equipment_description', models.CharField(max_length=40, verbose_name='Equipamentos de empreiteiras')),
                ('contractor_equipment_amount', models.IntegerField(verbose_name='Quantidade')),
                ('contractor_equipment_diary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Diary.Diary')),
            ],
        ),
        migrations.AddField(
            model_name='construction',
            name='construction_company_customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Diary.Customer'),
        ),
        migrations.AddField(
            model_name='construction',
            name='construction_company_engineer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Diary.Engineer'),
        ),
        migrations.CreateModel(
            name='Climate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('climate_morning', models.CharField(max_length=20, verbose_name='Clima da manhã')),
                ('climate_evening', models.CharField(max_length=20, verbose_name='Clima da tarde')),
                ('climate_diary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Diary.Diary')),
            ],
        ),
    ]
