# Generated by Django 3.0.6 on 2020-05-22 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Diary', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
