# Generated by Django 3.0.6 on 2020-05-25 22:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Diary', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Construction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('construction_name', models.CharField(max_length=60, verbose_name='Nome da construção')),
                ('construction_date_start', models.DateField(verbose_name='Data de início')),
                ('construction_date_term', models.DateField(verbose_name='Data de entrega')),
                ('construction_company_customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Diary.Customer')),
                ('construction_company_engineer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Diary.Engineer')),
            ],
        ),
        migrations.CreateModel(
            name='Diary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diary_date_day', models.DateField(verbose_name='Data do atual')),
                ('diary_construction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Diary.Construction')),
            ],
        ),
    ]
