# Generated by Django 3.0.6 on 2020-05-26 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Diary', '0003_direct_labor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Indirect_labor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indirect_labor_description', models.CharField(max_length=40, verbose_name='Mão de obra indireta')),
                ('indirect_labor_amount', models.IntegerField(verbose_name='Quantidade')),
                ('indirect_labor_diary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Diary.Diary')),
            ],
        ),
    ]
