# Generated by Django 3.0.6 on 2020-05-26 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Diary', '0005_contractor_labor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment_construction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipment_construction_description', models.CharField(max_length=40, verbose_name='Equipamentos da obra')),
                ('equipment_construction_amount', models.IntegerField(verbose_name='Quantidade')),
                ('equipment_construction_diary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Diary.Diary')),
            ],
        ),
    ]
