# Generated by Django 3.0.6 on 2020-05-26 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Diary', '0006_equipment_construction'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contractor_equipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contractor_equipment_description', models.CharField(max_length=40, verbose_name='Equipamentos de empreiteiras')),
                ('contractor_equipment_amount', models.IntegerField(verbose_name='Quantidade')),
                ('contractor_equipment_diary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Diary.Diary')),
            ],
        ),
    ]
