# Generated by Django 3.0.6 on 2020-05-26 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Diary', '0007_contractor_equipment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Climate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('climate_morning', models.CharField(max_length=20, verbose_name='Clima da manhã')),
                ('climate_evening', models.CharField(max_length=20, verbose_name='Clima da tarde')),
                ('climate_diary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Diary.Diary')),
            ],
        ),
    ]
