# Generated by Django 3.0.6 on 2020-05-26 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Diary', '0008_climate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Total_service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_service_manpower', models.IntegerField(verbose_name='Quantidade de mão de obra')),
                ('total_service_equipment', models.IntegerField(verbose_name='Quantidade de equipamento')),
            ],
        ),
    ]
