# Generated by Django 3.0.6 on 2020-05-26 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Diary', '0009_total_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='total_service',
            name='total_service_diary',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Diary.Diary'),
            preserve_default=False,
        ),
    ]
