# Generated by Django 3.0.6 on 2020-05-26 23:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Diary', '0010_total_service_total_service_diary'),
    ]

    operations = [
        migrations.CreateModel(
            name='Observation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observation_description_service', models.TextField(verbose_name='Descrição do serviço')),
                ('observation_description', models.TextField(verbose_name='Observações')),
                ('observation_diary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Diary.Diary')),
            ],
        ),
    ]
